name: simple_ui
description: "自定义简单 UI 组件"
version: 1.2.0
homepage: "https://github.com/yuzhido/simple_ui_for_flutter.git"
repository: "https://github.com/yuzhido/simple_ui_for_flutter.git"
issue_tracker: "https://github.com/yuzhido/simple_ui_for_flutter.git/issues"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  file_picker: ^10.2.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding packages, see
# https://flutter.dev/to/asset-from-package
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts, see
# https://flutter.dev/to/font-from-package
